name: Build and publish release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update package
        run: |
          version=$(curl -s https://hub.spigotmc.org/versions/ | \
            grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.json' | \
            sort -V | \
            tail -n 1 | \
            sed 's/\.json$//')
          echo "version=$version"
          
          docker_version=$(curl -s https://git.tulisiowice.top/Tulis/-/packages/container/tulibuilder/versions | \
            grep -oE 'v[0-9]+\.[0-9]+\.[0-9]' | \
            sort -V | \
            tail -n 1 | sed 's/^v//')
          echo "docker_version=$docker_version"
          
          if [ "$(printf '%s\n' "$version" "$docker_version" | sort -V | tail -n 1)" = "$version" ] && [ "$version" != "$docker_version" ]; then
              echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login git.tulisiowice.top -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
              docker build --build-arg MINECRAFT_VERSION=$version -t git.tulisiowice.top/tulis/tulibuilder:v$version .
              docker push git.tulisiowice.top/tulis/tulibuilder:v$version
          else
              echo "There's nothing to update!"
          fi