name: Build and publish release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Maven
        run: |
          version=$(curl -s https://hub.spigotmc.org/versions/ | \
            grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.json' | \
            sort -V | \
            tail -n 1 | \
            sed 's/\.json$//')

      - name: Download Java 21
        run: |
          echo $version